# Generated by Django 5.1 on 2024-09-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
